name: Continuous integration
on:
  push:
    branches:
      - main
      - develop*
  pull_request:
    branches:
      - main
      - develop*
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install Python packages
        run: |
          pip install .
          pip install ".[lint]"

      - name: Run isort
        run: isort --verbose --check --diff modflow_devtools

      - name: Run black
        run: black --check --diff modflow_devtools

      - name: Run flake8
        run: flake8 --count --show-source --exit-zero modflow_devtools

      - name: Run pylint
        run: pylint --jobs=0 --errors-only --exit-zero modflow_devtools
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Upgrade pip and install build and twine
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Base modflow_devtools installation
        run: |
          pip --verbose install .

      - name: Print package version
        run: |
          python -c "import modflow_devtools; print(modflow_devtools.__version__)"

      - name: Build package
        run: |
          python -m build
      
      - name: Check distribution
        run: |
          twine check --strict dist/*

  test:
    name: Test
    needs:
      - build
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ 3.8, 3.9, "3.10" ]
        exclude:
          # avoid shutil.copytree infinite recursion bug
          # https://github.com/python/cpython/pull/17098
          - python: '3.8.0'
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: modflow-devtools
      
      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6
      
      - name: Checkout modflow6 examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples
      
      - name: Checkout modflow6 test models
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-testmodels
          path: modflow6-testmodels
      
      - name: Checkout modflow6 large test models
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-largetestmodels
          path: modflow6-largetestmodels

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: modflow-devtools/setup.cfg

      - name: Install Python packages
        working-directory: modflow-devtools
        run: |
          pip install .
          pip install ".[test]"
      
      - name: Install extra Python packages
        working-directory: modflow6-examples/etc
        run: |
          pip install -r requirements.pip.txt
          pip install -r requirements.usgs.txt

      - name: Build modflow6 example models
        working-directory: modflow6-examples/etc
        run: python ci_build_files.py

      - name: Run tests
        working-directory: modflow-devtools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -v -n auto --durations 0