name: Publish release and package
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Upgrade pip and install build and twine
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Base modflow_devtools installation
        run: |
          pip --verbose install .

      - name: Print package version
        run: |
          python -c "import modflow_devtools; print(modflow_devtools.__version__)"

      - name: Build package
        run: |
          python -m build
      
      - name: Check distribution
        run: |
          twine check --strict dist/*
      
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
      
      # todo: set repo secrets and enable
      # - name: Publish package
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     twine upload dist/*